name: Deploy to AWS

on:
  push:
    branches:
      - master  # Trigger the workflow on push to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout your code

    - name: Set up AWS CLI 
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use AWS Access Key from secrets
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use AWS Secret Key from secrets
        aws-region: ap-south-1  # AWS region
        # profile: my-profile  # Optional, if you're using a named profile

    - name: Deploy to AWS
      run: |
        aws s3 sync dist/ s3://reshbuckets  # Sync files to S3 bucket
